language: generic
sudo: required
services:
    - docker

before_install:
    - cd frontend
    - docker build -t teemo2020/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true teemo2020/docker-react npm run test