language: generic
sudo: required
services:
    - docker

before_install:
    - cd frontend
    - docker build -t teemo2020/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true teemo2020/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-618983348966"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $aws_access_key
    secret_access_key: $aws_secret_key