apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: elucy-tls
spec:
    secretName: elucy-ml
    issuerRef: 
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: elucy.ml
    dnsNames:
        - elucy.ml
        - www.elucy.ml
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - elucy.ml
                - www.elucy.ml